import{a as q,S as B,i}from"./assets/vendor-Bbadc3Tp.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const M="55203157-9703e432d06ec35062b99b950",$="https://pixabay.com/api/";async function h(o,t=1){return(await q.get($,{params:{key:M,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const y=document.querySelector(".gallery"),d=document.querySelector(".loader"),u=document.querySelector(".load-more");let P=new B(".gallery a",{captionsData:"alt",captionDelay:250});function p(o){const t=o.map(({webformatURL:s,largeImageURL:l,tags:e,likes:r,views:a,comments:v,downloads:S})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${l}">
          <img class="gallery-image" src="${s}" alt="${e}" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b>${r}</p>
          <p class="info-item"><b>Views</b>${a}</p>
          <p class="info-item"><b>Comments</b>${v}</p>
          <p class="info-item"><b>Downloads</b>${S}</p>
        </div>
      </li>`).join("");y.insertAdjacentHTML("beforeend",t),P.refresh()}function x(){y.innerHTML=""}function b(){d&&d.classList.remove("is-hidden")}function L(){d&&d.classList.add("is-hidden")}function w(){u&&u.classList.remove("is-hidden")}function m(){u&&u.classList.add("is-hidden")}const g=document.querySelector(".form"),E=document.querySelector(".load-more");let c="",n=1,f=1;g.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.target.elements["search-text"].value.trim(),n=1,!c){i.warning({message:"Please enter a search term"});return}x(),m(),b();try{const t=await h(c,n);t.hits.length===0?i.error({message:"Sorry, no images found."}):(p(t.hits),f=Math.ceil(t.totalHits/15),f>1?w():i.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"}))}catch{i.error({message:"Something went wrong!"})}finally{L(),g.reset()}});E.addEventListener("click",async()=>{n+=1,m(),b();try{const o=await h(c,n);p(o.hits);const t=document.querySelector(".gallery-item");if(t){const{height:s}=t.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}n>=f?(m(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"})):w()}catch{i.error({message:"Error loading more images."})}finally{L()}});
//# sourceMappingURL=index.js.map
