import{a as q,S as B,i as a}from"./assets/vendor-Bbadc3Tp.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const M="55203157-9703e432d06ec35062b99b950",$="https://pixabay.com/api/";async function y(o,t=1){return(await q.get($,{params:{key:M,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const p=document.querySelector(".gallery"),d=document.querySelector(".loader"),u=document.querySelector(".load-more");let P=new B(".gallery a",{captionsData:"alt",captionDelay:250});function h(o){const t=o.map(({webformatURL:s,largeImageURL:l,tags:e,likes:r,views:i,comments:S,downloads:v})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${l}">
          <img class="gallery-image" src="${s}" alt="${e}" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b>${r}</p>
          <p class="info-item"><b>Views</b>${i}</p>
          <p class="info-item"><b>Comments</b>${S}</p>
          <p class="info-item"><b>Downloads</b>${v}</p>
        </div>
      </li>`).join("");p.insertAdjacentHTML("beforeend",t),P.refresh()}function x(){p.innerHTML=""}function b(){d&&d.classList.remove("is-hidden")}function L(){d&&d.classList.add("is-hidden")}function w(){u&&u.classList.remove("is-hidden")}function f(){u&&u.classList.add("is-hidden")}const g=document.querySelector(".form"),E=document.querySelector(".load-more");let c="",n=1,m=1;g.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.target.elements["search-text"].value.trim(),n=1,!c){a.warning({message:"Please enter a search term"});return}x(),f(),b();try{const t=await y(c,n);t.hits.length===0?a.error({message:"Sorry, no images found."}):(h(t.hits),m=Math.ceil(t.totalHits/15),m>1&&w())}catch{a.error({message:"Something went wrong!"})}finally{L(),g.reset()}});E.addEventListener("click",async()=>{n+=1,f(),b();try{const o=await y(c,n);h(o.hits);const t=document.querySelector(".gallery-item");if(t){const{height:s}=t.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}n>=m?(f(),a.info({message:"We're sorry, but you've reached the end of search results."})):w()}catch{a.error({message:"Error loading more images."})}finally{L()}});
//# sourceMappingURL=index.js.map
